
#############################################################################
### Taxonomy configuration ##################################################
#############################################################################
# This sets up the iXBRL taxonomy.  There should be a filename and a
# taxonomy ID.
taxonomy: //import taxonomy/ct-dpl.yaml

# CSS style
style: //import config/style.yaml

#############################################################################
### Report computations #####################################################
#############################################################################
computations:

##############################
# Detailed Profit and Loss ###
##############################

# Income 1.  Rounded, because the down-stream corptax service needs turnover
# to be rounded.
- id: income
  kind: round
  description: Income from main trade
  period: in-year
  direction: down
  segments:
    activity: m
    detailed-analysis: item1
    countries-regions: UK
  input:
    kind: line
    period: in-year
    accounts:
    - Income

# Turnover
- id: turnover
  kind: group
  description: Turnover / revenue
  period: in-year
  inputs:
  - income

# Gross profit
- id: gross-profit
  kind: sum
  description: Gross profit
  period: in-year
  inputs:
  - turnover

# Salaries expenditure
- id: salaries
  kind: line
  description: Salaries
  period: in-year
  segments:
    expense-type: administrative-expenses
  accounts:
  - Expenses:Emoluments:Employees

# Pension contributions
- id: pensions
  kind: line
  description: Pension contributions
  period: in-year
  segments:
    expense-type: administrative-expenses
  accounts:
  - Expenses:Emoluments:Employer Pension Contribution

# Bank charges
- id: bank-charges
  kind: line
  description: Bank charges
  period: in-year
  segments:
    expense-type: administrative-expenses
  accounts:
  - Expenses:VAT Purchases:Bank Charges

# Office costs
- id: office
  kind: line
  description: Office costs
  period: in-year
  segments:
    expense-type: administrative-expenses
  accounts:
  - Expenses:VAT Purchases:Office

# Software expenses
- id: software-expenses
  kind: line
  description: Software
  period: in-year
  segments:
    expense-type: administrative-expenses
  accounts:
  - Expenses:VAT Purchases:Software

# Sundries expenses
- id: sundries
  description: Sundries
  kind: line
  period: in-year
  segments:
    expense-type: administrative-expenses
  accounts:
  - Expenses:VAT Purchases:Sundries

# Travel / accomodation expenses
- id: travel
  description: Travel
  kind: line
  period: in-year
  segments:
    expense-type: administrative-expenses
  accounts:
  - Expenses:VAT Purchases:Travel/Accom

# Accountancy costs
- id: accountancy
  description: Accountancy services
  kind: line
  period: in-year
  segments:
    expense-type: administrative-expenses
  accounts:
  - Expenses:VAT Purchases:Accountant

# Subscriptions
- id: subscriptions-costs
  kind: line
  description: Subscriptions
  period: in-year
  segments:
    expense-type: administrative-expenses
  accounts:
  - Expenses:VAT Purchases:Subscriptions

# Telecoms
- id: telecoms
  kind: line
  description: Telecoms
  period: in-year
  segments:
    expense-type: administrative-expenses
  accounts:
  - Expenses:VAT Purchases:Telecoms

# Total costs, the sum of the above.
- id: total-costs
  description: Total costs
  kind: group
  period: in-year
  inputs:
  - salaries
  - pensions
  - accountancy
  - bank-charges
  - office
  - software-expenses
  - subscriptions-costs
  - sundries
  - telecoms
  - travel

# Profit before tax
- id: profit-before-tax
  kind: group
  description: Net profit before tax
  inputs:
  - gross-profit
  - total-costs
  period: in-year

# Corporation tax, from the accounts
- id: corporation-tax
  kind: line
  description: Corporation tax
  period: in-year
  accounts:
  - Equity:Corporation Tax

# Tax due (just the above)
- id: tax-due
  description: Corporation tax
  kind: sum
  period: in-year
  inputs:
  - corporation-tax

- id: profit
  kind: sum
  description: Profit (Loss) after tax
  period: in-year
  inputs:
  - profit-before-tax
  - tax-due

##############################
# R&D expenditure at 130% ####
##############################

# First project staffing
- id: rnd-proj1-enhanced-staffing
  description: Staffing (@ 130%)
  kind: round
  direction: down
  period: in-year
  segments:
    business-name: metadata.business.company-name
    business-type: trade
    ct-detailed-analysis: item1
    loss-reform: post-loss-reform
    territory: uk
  input:
    kind: line
    period: in-year
    accounts:
    - R&D Enhanced Expenditure:Expenditure:Project Iguana:Staffing Costs

# First project external workers
- id: rnd-proj1-enhanced-external
  description: External workers (@ 130%)
  kind: round
  period: in-year
  direction: down
  segments:
    business-name: metadata.business.company-name
    business-type: trade
    ct-detailed-analysis: item1
    loss-reform: post-loss-reform
    territory: uk
  input:
    kind: line
    period: in-year
    accounts:
    - R&D Enhanced Expenditure:Expenditure:Project Iguana:External Workers

# First project external software/consumable
- id: rnd-proj1-enhanced-software
  description: Software/Consumables (@ 130%)
  kind: round
  period: in-year
  direction: down
  segments:
    business-name: metadata.business.company-name
    business-type: trade
    ct-detailed-analysis: item1
    loss-reform: post-loss-reform
    territory: uk
  input:
    kind: line
    period: in-year
    accounts:
    - R&D Enhanced Expenditure:Expenditure:Project Iguana:Software/Consumables

# First project total
- id: rnd-proj1-enhanced-expenditure
  kind: group
  description: Project Iguana
  period: in-year
  segments:
    business-name: metadata.business.company-name
    business-type: trade
    ct-detailed-analysis: item1
    loss-reform: post-loss-reform
    territory: uk
  inputs:
  - rnd-proj1-enhanced-staffing
  - rnd-proj1-enhanced-software
  - rnd-proj1-enhanced-external

# All R&D total
- id: rnd-enhanced-expenditure
  kind: group
  description: SME R&D tax relief (130%)
  period: in-year
  segments:
    business-name: metadata.business.company-name
    business-type: trade
    loss-reform: post-loss-reform
    territory: uk
  inputs:
  - rnd-proj1-enhanced-expenditure

##############################
# Tax computation ############
##############################

# Annual investment allowance
- id: ct-annual-investment-allowance
  kind: round
  description: Annual investment allowance
  period: in-year
  direction: down
  segments:
    business-type: management-expenses
  input:
    kind: line
    period: in-year
    reverse-sign: true
    segments:
      business-type: management-expenses
    accounts:
    - Assets:Capital Equipment:Computer Equipment

# Profit (loss) from DPL
- id: profit-loss-per-accounts
  kind: sum
  description: Profit (loss) per accounts
  period: in-year
  segments:
    business-name: metadata.business.company-name
    business-type: trade
    loss-reform: post-loss-reform
    territory: uk
  inputs:
  - profit-before-tax

# Trading profits
- id: ct-trading-profits-raw
  kind: group
  description: Taxable profits
  period: in-year
  segments:
    business-type: company
  inputs:
  - profit-loss-per-accounts
  - ct-annual-investment-allowance
  - rnd-enhanced-expenditure

- id: ct-trading-profits
  kind: round
  description: Taxable profits
  input: ct-trading-profits-raw
  direction: down
  period: in-year
  segments:
    business-type: company

# Profits chargeable to corp tax
- id: ct-profits
  kind: group
  description: Profits chargeable to corporation tax
  period: in-year
  segments:
    business-type: company
  inputs:
  - ct-trading-profits

# Profits apportioned to first FY
- id: ct-profit-before-tax-fy1
  kind: round
  description: FY1
  period: in-year
  direction: nearest
  input:
    kind: apportion
    description: FY1
    period: in-year
    input: ct-profits
    whole-period: metadata.report.periods.0
    proportion-period: metadata.tax.fy1
  segments:
    business-type: company

# Profits apportioned to second FY
- id: ct-profit-before-tax-fy2
  kind: round
  description: FY2
  period: in-year
  direction: nearest
  input:
    kind: apportion
    description: FY2
    period: in-year
    input: ct-profits
    whole-period: metadata.report.periods.0
    proportion-period: metadata.tax.fy2
  segments:
    business-type: company

# Total of FY1 and FY2 profits.  Visual check on the worksheet, should be the
# same as profits chargeable to corp tax
- id: ct-profit-before-tax-total
  description: Profits, by financial year
  kind: group
  period: in-year
  inputs:
  - ct-profit-before-tax-fy1
  - ct-profit-before-tax-fy2
  segments:
    business-type: company

# Tax due on FY1
- id: ct-tax-fy1
  kind: factor
  description: FY1 (19%)
  factor: -0.19
  period: in-year
  input: ct-profit-before-tax-fy1
  reverse-sign: true
  segments:
    business-type: company

# Tax due in FY2
- id: ct-tax-fy2
  kind: factor
  description: FY2 (19%)
  factor: -0.19
  period: in-year
  input: ct-profit-before-tax-fy2
  reverse-sign: true
  segments:
    business-type: company

# Total tax due
- id: ct-tax-total
  description: Corporation tax chargeable
  kind: group
  inputs:
  - ct-tax-fy1
  - ct-tax-fy2
  period: in-year
  segments:
    business-type: company

# Tax owed
- id: ct-tax-owed
  kind: sum
  inputs: [ct-tax-total]

#############################################################################
### Worksheets ##############################################################
#############################################################################
worksheets:

# Research and development costs
- id: rnd
  kind: multi-period
  description: SME R&D
  computations:
  - rnd-proj1-enhanced-expenditure
  - rnd-enhanced-expenditure

# Tax calculation
- id: tax-calculation
  kind: multi-period
  description: Tax Calculation
  computations:
  - ct-trading-profits-raw
  - ct-profits
  - ct-profit-before-tax-total
  - ct-tax-total

# Detailed profit and loss
- id: detailed-profit-and-loss
  kind: multi-period
  description: Detailed Profit-and-Loss
  computations:
  - turnover
  - gross-profit
  - total-costs
  - profit-before-tax
  - tax-due
  - profit

# Report elements
elements:
- id: report
  kind: composite
  elements:
  - about
  - capital-allowances
  - profits
  - tax-chargeable
  - rnd-creative-enhanced-expenditure
  - rnd
  - detailed-profit-and-loss
  - tax-calculation

- id: about
  kind: page
  elements:
  - kind: facttable
    title: Corporation Tax Return
    facts:
    - id: company-name
      kind: config
      description: Company name
      field: '1'
      context: report-date
      key: metadata.business.company-name
    - context: report-date
      description: Tax reference
      field: '3'
      id: tax-reference
      key: metadata.tax.utr
      kind: config
    - context: report-date
      description: Return period start
      field: '30'
      id: return-period-start
      key: metadata.tax.period.start
      kind: config-date
    - context: report-date
      description: Return period end
      field: '35'
      id: return-period-end
      key: metadata.tax.period.end
      kind: config-date
    - context: report-date
      description: Start of accounts period
      field: '-'
      id: account-period-start
      key: metadata.tax.period.start
      kind: config-date
    - context: report-date
      description: End of accounts period
      field: '-'
      id: account-period-end
      key: metadata.tax.period.end
      kind: config-date
    - context: report-period
      description: Company is a partner in a firm
      field: '-'
      id: partner-in-a-firm
      kind: bool
      value: false

- id: capital-allowances
  kind: page
  elements:
  - kind: facttable
    title: Capital allowances and balancing charges
    facts:
    - id: annual-investment-allowance
      context: report-period
      description: Annual investment allowance
      field: '690'
      computation: ct-annual-investment-allowance
      kind: computation
      period-config: metadata.tax.period
      context: management-expenses-period

- id: profits
  kind: page
  elements:
  - kind: facttable
    title: Profits and gains
    facts:
    - id: adjusted-trading-profit-of-this-period
      context: report-period
      description: Trading profits
      field: '155'
      computation: ct-trading-profits
      kind: computation
      period-config: metadata.tax.period
    - id: trading-losses-brought-forward
      description: Trading losses brough forward
      field: 160, 285
      context: report-period
      kind: money
      value: 0
    - id: net-trading-profits
      computation: ct-trading-profits
      context: report-period
      description: Net trading profits
      field: '165'
      kind: computation
      period-config: metadata.tax.period
    - context: report-period
      description: Net chargeable gains
      field: '220'
      id: net-chargeable-gains
      kind: money
      value: 0
      period-config: metadata.tax.period
    - id: profits-before-other-deductions-and-reliefs
      computation: ct-trading-profits
      context: report-period
      description: Profits before other deductions and reliefs
      field: '235'
      kind: computation
      period-config: metadata.tax.period
    - id: profits-before-charges-and-group-relief
      kind: computation
      computation: ct-profits
      context: report-period
      description: Profits before donations and group relief
      field: '300'
      period-config: metadata.tax.period
    - id: qualifying-donations
      context: report-period
      description: Qualifying donations
      field: '305'
      kind: money
      value: 0
    - context: report-period
      description: Group relief
      field: '310'
      id: group-relief-claimed
      kind: money
      value: 0
    - context: report-period
      description: Group relief for carried forward losses
      field: '312'
      id: group-relief-claimed-for-carried-forward-losses
      kind: money
      value: 0
    - computation: ct-profits
      context: report-period
      description: Profits chargeable to Corporation Tax
      field: '315'
      id: total-profits-chargeable-to-corporation-tax
      kind: computation
      period-config: metadata.tax.period

- id: tax-chargeable
  kind: page
  elements:
  - kind: facttable
    title: Tax chargeable
    facts:
    - id: financial-year1-covered-by-the-return
      context: report-period
      description: Financial year 1 covered by the return
      field: '330'
      kind: string
      value: '2019'
    - id: financial-year2-covered-by-the-return
      context: report-period
      description: Financial year 2 covered by the return
      field: '380'
      kind: string
      value: '2020'
    - id: fy1-amount-of-profit-chargeable-at-first-rate
      context: report-period
      description: FY1 profit chargeable at first rate
      field: '335'
      computation: ct-profit-before-tax-fy1
      kind: computation
      period-config: metadata.tax.period
    - id: fy2-amount-of-profit-chargeable-at-first-rate
      context: report-period
      description: FY2 profit chargeable at first rate
      field: '385'
      computation: ct-profit-before-tax-fy2
      kind: computation
      period-config: metadata.tax.period
    - id: fy1-first-rate-of-tax
      context: report-period
      description: FY1 first rate of tax (%)
      field: '340'
      kind: number
      value: 19
    - id: fy2-first-rate-of-tax
      context: report-period
      description: FY2 first rate of tax (%)
      field: '390'
      kind: number
      value: 19
    - id: fy1-tax-at-first-rate
      computation: ct-tax-fy1
      context: report-period
      description: FY1 tax at first rate
      field: '345'
      kind: computation
      period-config: metadata.tax.period
    - id: fy2-tax-at-first-rate
      computation: ct-tax-fy2
      context: report-period
      description: FY2 tax at first rate
      field: '395'
      kind: computation
      period-config: metadata.tax.period
    - id: corporation-tax-chargeable
      computation: ct-tax-total
      context: report-period
      description: Corporation tax
      field: '430'
      kind: computation
      period-config: metadata.tax.period
    - context: report-period
      description: Marginal relief for ring fence trades
      field: '435'
      id: marginal-rate-relief-for-ring-fence-trades-payable
      kind: money
      value: 0
    - computation: ct-tax-owed
      context: report-period
      description: Corporation tax chargeable
      field: '440'
      id: corporation-tax-chargeable-payable
      kind: computation
      period-config: metadata.tax.period
    - id: total-reliefs-and-deductions-in-terms-of-tax-payable
      context: report-period
      description: Total reliefs and deduction in terms of tax
      field: '470'
      kind: money
      value: 0
      period-config: metadata.tax.period
    - id: net-corporation-tax-payable
      kind: computation
      context: report-period
      computation: ct-tax-owed
      description: Net Corporation Tax liability
      field: '475'
      period-config: metadata.tax.period
    - id: tax-chargeable
      kind: computation
      context: report-period
      computation: ct-tax-owed
      description: Tax chargeable
      field: '510'
      period-config: metadata.tax.period
    - id: tax-payable
      kind: computation
      context: report-period
      computation: ct-tax-owed
      description: Tax payable
      field: '525'
      period-config: metadata.tax.period

- id: rnd-creative-enhanced-expenditure
  kind: page
  elements:
  - kind: facttable
    title: R&D / Creative enhanced expenditure
    facts:

    - id: rnd-enhanced-sme
      description: Small or medium-sized enterprise
      field: '650'
      context: report-period
      kind: bool
      value: true

    - id: rnd-enhanced-large
      description: Large company
      field: '655'
      context: report-period
      kind: bool
      value: false

    - id: rnd-enhanced-expenditure
      kind: computation
      description: R&D enhanced expenditure
      field: '660'
      context: trade-period
      computation: rnd-enhanced-expenditure
      period-config: metadata.tax.period

    - id: creative-enhanced-expenditure
      kind: money
      description: Creative enhanced expenditure
      field: '665'
      context: trade-period
      value: 0
      period-config: metadata.tax.period

    - id: rnd-creative-enhanced-expenditure
      kind: computation
      description: R&D / Creative enhanced expenditure
      field: '670'
      context: report-period
      computation: rnd-enhanced-expenditure
      period-config: metadata.tax.period

    - id: rnd-enhanced-expenditure-subcontracted
      kind: money
      description: R&D subcontracted by a large company
      field: '675'
      context: report-period
      value: 0
      period-config: metadata.tax.period

- id: rnd
  kind: page
  elements:
  - kind: worksheet
    title: SME R&D
    worksheet: rnd

- id: tax-calculation
  kind: page
  elements:
  - kind: worksheet
    title: Tax calculation
    worksheet: tax-calculation

- id: detailed-profit-and-loss
  kind: page
  elements:
  - kind: worksheet
    title: Detailed Profit-and-Loss
    worksheet: detailed-profit-and-loss
