
#############################################################################
### GnuCash accounts source #################################################
#############################################################################
accounts:
  # Filename of GnuCash accounts
  file: example.gnucash

#############################################################################
### Taxonomy configuration ##################################################
#############################################################################
# This sets up the iXBRL taxonomy.  There should be a filename and a
# taxonomy ID.
taxonomy:
  file: taxonomy/frs102.yaml
  id: frs102

#############################################################################
### Report metadata #########################################################
#############################################################################
# Metadata used in reports.  Note that some of the metadata here is only
# referenced from the taxonomy files, so different taxonomies will demand
# different metadata.
metadata:

  # Metadata about the business
  business:

    # Summary of business activities
    activities: Computer security consultancy and development services

    # Average number of employees over the previous 2 accounting periods
    average-employees:
    - 2
    - 1

    # Business name
    company-name: Example Biz Ltd.

    # Registered company number
    company-number: '12345678'

    # iXBRL entity scheme, Companies House
    entity-scheme: http://www.companieshouse.gov.uk/

    # Legal entity formation information
    company-formation:
      country: england-and-wales
      date: '2017-04-05'
      form: private-limited-company

    # VAT registration number
    vat-registration: GB012345678

    # Company contact details
    contact:

      # Contact name, address, county, location (city), country, email
      name: Corporate Enquiries
      address:
      - 123 Leadbarton Street
      - Dumpston Trading Estate
      county: Minchingshire
      location: Threapminchington
      postcode: QQ99 9ZZ
      country: UK
      email: corporate@example.org

      # Phone number
      phone:
        area: '7900'
        country: '+44'
        number: '0123456'
        type: landline

    # Directors of the business
    directors:
    - A Bloggs
    - B Smith
    - C Jones

    # Industry sector.  Search for uk-bus:MainIndustrySectorDimension in the
    # taxonomy file.
    industry-sector: m

    # Is the company dormant?
    is-dormant: false

    # SIC codes registered with Companies House.
    sic-codes:
    - '62020'
    - '62021'

    # Contact website description and URL
    website:
      description: Corporate website
      url: https://example.org/corporate

  # Report metadata
  report:

#    pretty-print: true

    # The accounting-standards applied.  One of:
    #   frs101, frs102, frsse, full-irs, micro-entities, other-standards,
    #   small-entities-regime.
    accounting-standards: micro-entities

    # Accounts status, one of:
    #   audit-exempt-no-accountants-report,
    #   audit-exempt-with-accountants-report, audited,
    #   independent-examination, other-reporting-regime
    accounts-status: audit-exempt-no-accountants-report

    # Accounts type, one of:
    #   abbreviated-accounts, abridged-accounts, full-accounts
    accounts-type: abridged-accounts

    # Date report was authorised for issue
    authorised-date: '2021-01-01'

    # Date of the balance sheet data pull
    balance-sheet-date: '2020-12-31'

    # Accounts currency
    currency: GBP

    # Report issue date
    date: '2021-01-01'

    # Periods over which the account was issued.  Current period goes first.
    periods:
    - name: '2020'
      start: '2020-01-01'
      end: '2020-12-31'
    - name: '2019'
      start: '2019-01-01'
      end: '2019-12-31'

    # Name of director who signed the reports
    signed-by: B Smith

    # Context segment of the director who signed the report.  director2
    # means the second director in the list metadata.business.directors.
    signing-officer: director2

    # Report title
    title: Unaudited Micro-Entity Accounts

  # Tax details, used by the Corporation tax profile
  tax:

    # Unique Taxpayer Reference (HMRC issued)
    utr: '8596148860'

    # Tax period
    period:
      name: '2021'
      start: '2020-02-01'
      end: '2021-01-31'

#############################################################################
### Report computations #####################################################
#############################################################################
computations:


##############################
# Income statement ###########
##############################

# Income from consultancy
- id: consultancy
  kind: line
  description: Consultancy
  period: in-year
  accounts:
  - Income

# Total turnover
- id: turnover
  kind: group
  description: Turnover / revenue
  hide-breakdown: true
  period: in-year
  inputs:
  - consultancy

# Gross profit
- id: gross-profit
  kind: sum
  description: Gross Profit
  period: in-year
  inputs:
  - turnover

# Salaries expense
- id: salaries
  kind: line
  accounts:
  - Expenses:Emoluments:Employees
  description: Salaries
  period: in-year

# Pension contributions expense
- id: pensions
  kind: line
  accounts:
  - Expenses:Emoluments:Employer Pension Contribution
  description: Pension contributions
  period: in-year

# Depreciation - not calculated, just taken out of the depreciation expense
# account
- id: depreciation
  kind: line
  description: Depreciation
  accounts:
  - Expenses:Depreciation
  period: in-year

# Accountancy expenses
- id: accountancy
  kind: line
  description: Accountancy services
  accounts:
  - Expenses:VAT Purchases:Accountant
  period: in-year

# Bank charges
- id: bank-charges
  kind: line
  description: Bank charges
  period: in-year
  accounts:
  - Expenses:VAT Purchases:Bank Charges

# Office expenses
- id: office
  kind: line
  description: Office costs
  period: in-year
  accounts:
  - Expenses:VAT Purchases:Office

# Software expenses
- id: software
  kind: line
  description: Software
  period: in-year
  accounts:
  - Expenses:VAT Purchases:Software

# Subscriptions
- id: subscriptions
  kind: line
  description: Subscriptions
  period: in-year
  accounts:
  - Expenses:VAT Purchases:Subscriptions

# Sundries
- id: sundries
  kind: line
  description: Sundries
  period: in-year
  accounts:
  - Expenses:VAT Purchases:Sundries

# Telecoms
- id: telecoms
  kind: line
  description: Telecoms
  period: in-year
  accounts:
  - Expenses:VAT Purchases:Telecoms

# Travel and accomodation
- id: travel
  kind: line
  description: Travel
  period: in-year
  accounts:
  - Expenses:VAT Purchases:Travel/Accom
  
# Administrative expenses total, sums all the expenses above.
- id: administrative-expenses
  kind: group
  description: Administrative Expenses
  hide-breakdown: true
  inputs:
  - salaries
  - pensions
  - depreciation
  - accountancy
  - bank-charges
  - office
  - software
  - subscriptions
  - sundries
  - telecoms
  - travel
  period: in-year

# Profit, computed from gross profit without the expenses
- id: profit
  kind: sum
  description: Profit (Loss)
  period: in-year
  inputs:
  - gross-profit
  - administrative-expenses


##############################
# Balance sheet ##############
##############################

# Tanglible assets is taken from the Capital Equipment account in GnuCash
- id: tangible-assets
  kind: line
  description: Tangible Assets
  period: at-end
  accounts:
  - Assets:Capital Equipment
  
# Fixed assets is tangible assets
- id: fixed-assets
  description: Fixed Assets
  kind: sum
  period: at-end
  inputs:
  - tangible-assets

# Debtors
- id: debtors
  kind: line
  description: Debtors
  period: at-end
  accounts:
  - Accounts Receivable
  - Assets:Owed To Us

# VAT due back
- id: vat-refund-owed
  kind: line
  description: VAT Refund Due
  period: at-end
  accounts:
  - VAT:Input

# Cash in bank
- id: bank
  kind: line
  description: Bank
  period: at-end
  accounts:
  - Bank Accounts

# Current assets
- id: current-assets
  kind: sum
  description: Current Assets
  inputs:
  - debtors
  - vat-refund-owed
  - bank

# These accounts don't have any prepayments / accrued income
- id: prepayments-and-accrued-income
  kind: group
  description: Prepayments and Accrued Income
  inputs: []

# Trade creditors
- id: trade-creditors
  kind: line
  description: Trade Creditors
  period: at-end
  accounts:
  - Accounts Payable

# Other creditrs
- id: other-creditors
  kind: line
  description: Other Creditors
  period: at-end
  accounts:
  - VAT:Output

# Creditors owing amounts which are due within 1 year.
- id: creditors-within-1-year
  kind: sum
  description: 'Creditors: falling due within one year'
  inputs:
  - trade-creditors
  - other-creditors
  # In the FRS taxonomies there is a dimension which partitions
  # creditors due within 1 year from over 1 year
  segments:
    matures: within-1-year

# Net current assets
- id: net-current-assets
  kind: sum
  description: Net Current Assets
  inputs:
  - current-assets
  - prepayments-and-accrued-income
  - creditors-within-1-year

# Total assets less liabilities - adds fixed assets
- id: total-assets-less-liabilities
  kind: sum
  description: Total Assets Less Liabilities
  inputs:
  - fixed-assets
  - current-assets
  - prepayments-and-accrued-income
  - creditors-within-1-year

# Creditors owing amounts which are due beyond 1 year
- id: creditors-after-1-year
  kind: group
  description: 'Creditors: falling due after one year'
  inputs: []
  segments:
    matures: after-1-year

# Corporation tax liability
- id: corporation-tax-owed
  kind: line
  description: Corporation Tax
  period: at-end
  accounts:
  - Liabilities:Owed Corporation Tax

# Liabilities
- description: Provisions For Liabilities
  id: provisions-for-liabilities
  kind: sum
  inputs:
  - corporation-tax-owed

# Accrued liabilities and deferred income (we have none)
- id: accruals-and-deferred-income
  kind: group
  description: Accrued liabilities and deferred income
  inputs: []

# Net assets
- id: net-assets
  kind: sum
  description: Net Assets
  inputs:
  - total-assets-less-liabilities
  - creditors-after-1-year
  - provisions-for-liabilities
  - accruals-and-deferred-income

# Called-up share capital
- id: share-capital
  kind: line
  description: Share Capital
  period: at-end
  accounts:
  - Equity:Shareholdings

# Profit i.e. income minus expenses.
- id: profit-loss
  kind: line
  description: Retained Profit
  period: at-end
  accounts:
  - Income
  - Expenses

# Dividends paid out
- id: dividends
  kind: line
  description: Dividends
  period: at-end
  accounts:
  - Equity:Dividends

# Corporation tax drawn on the equity account
- id: corporation-tax
  kind: line
  description: Corporation Tax
  period: at-end
  accounts:
  - Equity:Corporation Tax

# Capital and reserves is the equity total
- description: Capital and Reserves
  id: capital-and-reserves
  kind: group
  inputs:
  - share-capital
  - profit-loss
  - dividends
  - corporation-tax

# Capital total
- id: total-capital-and-reserves
  kind: sum
  description: Total Capital and Reserves
  inputs:
  - capital-and-reserves


##############################
# Fixed assets ###############
##############################

# Fixed assets at start of period
- id: fixed-assets-initial
  kind: line
  description: At start of period
  period: at-start
  accounts:
  - Assets:Capital Equipment:Computer Equipment

# Changes to fixed assets over the period
- id: fixed-assets-additions
  kind: line
  description: Additions
  period: in-year
  accounts:
  - Assets:Capital Equipment:Computer Equipment

# Fixed assets at end of period (sum of the above two)
- id: fixed-assets-total
  kind: group
  description: Fixed Assets
  inputs:
  - fixed-assets-initial
  - fixed-assets-additions

# Depreciation is accrued as a charge from the outset of the business.
# This is the initial value at the start of the period
- id: depreciation-initial
  kind: line
  description: At start of period
  period: at-start
  accounts:
  - Assets:Capital Equipment:Depreciation

# Depreciation addition over the period
- id: depreciation-charge
  kind: line
  description: Charge
  period: in-year
  accounts:
  - Assets:Capital Equipment:Depreciation

# Depreciation at end of period (sum of above two)
- id: depreciation-total
  kind: group
  description: Depreciation
  inputs:
  - depreciation-initial
  - depreciation-charge

# Assets carried is fixed assets at end of period minus depreciation at end
# of period
- id: carrying-final
  kind: sum
  description: Carrying at end of period
  inputs:
  - fixed-assets-total
  - depreciation-total

##############################
# Shareholdings ##############
##############################

# Ordinary shares held at start of period
- id: ordinary-shares-at-start
  kind: line
  description: Ordinary Shares
  period: at-start
  accounts:
  - Equity:Shareholdings:Ordinary Shares

# Preference shares held at start
- id: preference-shares-at-start
  kind: line
  description: Preference Shares
  period: at-start
  accounts:
  - Equity:Shareholdings:Preference Shares

# Shares issued
- id: shares-issued
  kind: line
  description: Shares Issued
  period: in-year
  accounts:
  - Equity:Shareholdings

# Share capital total is sum of the above 3.
- id: share-capital
  kind: group
  description: Share Capital
  period: at-end
  inputs:
  - ordinary-shares-at-start
  - preference-shares-at-start
  - shares-issued

#############################################################################
### Worksheets ##############################################################
#############################################################################
# Worksheets list the computations which are shown on each accounting figure
worksheets:

# Balance sheet
- id: balance-sheet
  kind: multi-period
  computations:
  - fixed-assets
  - current-assets
  - prepayments-and-accrued-income
  - creditors-within-1-year
  - net-current-assets
  - total-assets-less-liabilities
  - creditors-after-1-year
  - provisions-for-liabilities
  - accruals-and-deferred-income
  - net-assets
  - total-capital-and-reserves

# Profit and loss
- id: profit-and-loss
  kind: multi-period
  description: Profit and Loss
  computations:
  - turnover
  - gross-profit
  - administrative-expenses
  - profit

# Fixed assets
- id: fixed-assets
  kind: multi-period
  description: Fixed Assets
  computations:
  - fixed-assets-total
  - depreciation-total
  - carrying-final

# Share capital
- id: share-capital
  kind: multi-period
  description: Share Capital
  computations:
  - share-capital

#############################################################################
### Elements describe the report structure ##################################
#############################################################################

elements:

# Top-level report element is a composite which invokes the other elements.
# The top-level element adds iXBRL schema stuff and document metadata.
# That is configurable in the taxonomy, not here.
- id: report
  kind: composite
  elements:
  - title
  - balance-sheet
#  - profit-and-loss
  - notes

# Title page.
- id: title
  kind: title

  # Document wet-ink signature image.
  signature-image: signature.png
  signature-type: image/png

# Balance sheet
- id: balance-sheet
  kind: worksheet
  title: Balance Sheet
  worksheet: balance-sheet

# Profit and loss
- id: profit-and-loss
  kind: worksheet
  title: Income Statement
  worksheet: profit-and-loss

# Fixed assets
- id: fixed-assets
  kind: worksheet
  title: Fixed Assets
  worksheet: fixed-assets

# Share capital
- id: share-capital
  kind: worksheet
  title: Share Capital
  worksheet: share-capital

# Notes page at end
- id: notes
  kind: notes
  notes:

  # Some boilerplate notes...

  # ...prepared in accordance with the micro-entity provisions...
  - micro-entity-provisions

  # ...the company was entitled to exemption from audit..
  - small-company-audit-exempt

  # ...members have not required the company to obtain an audit..
  - no-audit-required

  # Company number and address.
  - company

  # ...directors acknowledge their responsibilities for complying with...
  - directors-acknowledge

  # These accounts were generated using gnucash-ixbrl...  You don't need
  # to have this one in your report.
  - software-version

  # Just showing how custom notes are created.
  - 'note:These are fictional accounts, ~[company-name] is intended to
    reference a fictional entity.  Any references to real-world entities or
    persons is unintentional.'

